baseURL = "http://localhost:1313/"
#baseURL = 'https://tabcaster.org/'
languageCode = 'en-us'
title = 'TabCaster'
theme = 'blowfish'
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10   
